witchdoctor:
  api:
    prefix: /api
  security:
    bCryptRounds: 12
spring:
  jpa:
    hibernate.ddl-auto: "create-drop"
  datasource:
    url: jdbc:postgresql://localhost:5432/witchdoctor
    username: postgres
    password: postgres
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
